services:
  - type: web
    name: nolab-reservations-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://nolab-technical.netlify.app/
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
    autoDeploy: true
